### ISSUE TITLE
Cannot test local video loopback in Licode Basic Example

### ISSUE THREAD

**Issue by ankur0101** [ging/licode#406]
Hi,
I ran 
https://mydomain.tld:3004/
for which I am unable to see my own local stream video.
After opening those mentioned URls, browser asks for sharing Camera and Audio method.
Once clicked Allow or share, It says "- Mic and Cam OK" in a text area.
However, I am unable to see my own local video loopback.
![Licode Local Video Issue](http://i.imgur.com/vvCE6UG.png)
Need help

**Comment by mosfet1kg** [comment]
You might get stressed because of this problem. But there aren't any logs to solve it so no one who help you also.  I think you didn't install licode in clean environment. I recommend that how about docker to deploy Licode?  Following link contains useful infomation https://github.com/ging/licode/issues/397

**Comment by nachoaguadoc** [comment]
Hi @ankur0101,

Can you give us more information about the logs in the web browser console?

**Comment by ankur0101** [comment]
@nachoaguadoc I will upload licode config and basic example js files shortly.

**Comment by nachoaguadoc** [comment]
@ankur0101 Is everything solved by now?
