### ISSUE TITLE
What is the purpose of MAuth realm marte3.dit.upm.es in Nuve libs?

### ISSUE THREAD

**Issue by zevarito** [ging/licode#465]
Hi,

We are getting randomly the below response from Nuve when requesting a token:

```json
owner_token = {"WWW-Authenticate":"MAuth realm=http://marte3.dit.upm.es"}
```

Looking for where `marte3.dit.upm.es` was coming from I've seen that it is present on all Nuve clients.
For example in Ruby client you can see it here: https://github.com/ging/licode/blob/master/nuve/nuveClient_ruby/nuve.rb#L58

What is the reason behind that?
Why Nuve is sending that string back instead of the Token sometimes?

**Comment by zevarito** [comment]
The reason that is not working sometimes looks like a fail checking timestamps due to a difference of seconds on Licode and App servers. NTP should fix that, still wondering if the realm should be hardcoded or not.

**Comment by lodoyun** [comment]
From RFC 2617.
The realm attribute (case-insensitive) is required for all authentication schemes which issue a challenge. The realm value (case-sensitive), in combination with the canonical root URL of the server being accessed, defines the protection space. These realms allow the protected resources on a server to be partitioned into a set of protection spaces, each with its own authentication scheme and/or authorization database. The realm value is a string, generally assigned by the origin server, which may have additional semantics specific to the authentication scheme.

In Nuve we don't really define different protection spaces within the same server so that field is mostly irrelevant but its standard for this kind of authentication mechanisms. The actual string is legacy code, in any case it won't affect your ability to authenticate.

You are getting the authentication challenge again because the requests is failing a step in the authorization process. You can see exactly what is going on in the nuve logs or [here](https://github.com/ging/licode/blob/master/nuve/nuveAPI/auth/nuveAuthenticator.js#L61)

**Comment by zevarito** [comment]
@lodoyun thanks for the explanation.
